name: CI of IDEAS using GitHub Actions
on: [push, pull_request]
jobs:
  test_job:
    runs-on: self-hosted
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server called tony-de-rekenpony hosted by The Sysis team at KU Leuven"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: chmod -R 777 /home/actions-runner/_work/IDEAS/IDEAS
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: chmod -R 777 /home/actions-runner/_work/IDEAS/IDEAS
      - name: List of files in the repository
        run: | 
         ls ${{ github.workspace }}
      - name: Run tests
        run: cd IDEAS/Resources/Scripts/tests && make test-dymola PACKAGE=\"IDEAS.Fluid.Taps\" INTERACTIVE=false