name: CI of IDEAS using GitHub Actions
on: [push, pull_request]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server called tony-de-rekenpony hosted by The Sysis team at KU Leuven"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          clean: true
      - name: Change permissions of repository folder
        run: chmod -R 777 /home/actions-runner/_work
      - name: List of files in the repository
        run: | 
         ls ${{ github.workspace }}
  test:
    runs-on: self-hosted
    needs: build
    defaults:
      run:
        - export INTERACTIVE=false
        working-directory: IDEAS/Resources/Scripts/tests
    steps:
      - name: check for INTERACTIVE
        run: echo "The value of INTERACTIVE IS $INTERACTIVE"