name: CI of IDEAS using GitHub Actions
on: [push, pull_request]
env:
  INTERACTIVE: "false"
jobs:
  test_job:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: IDEAS/Resources/Scripts/tests
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server called tony-de-rekenpony hosted by The Sysis team at KU Leuven"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          clean: true
      - name: Change permissions of repository folder
        run: chmod -R 777 /home/actions-runner/_work
      - name: List of files in the repository
        run: | 
         ls ${{ github.workspace }}
      - name: Test IDEAS.Fluid.Actuators
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Actuators\"
      - name: Test IDEAS.Fluid.BaseClasses
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.BaseClasses\"
