name: CI of IDEAS using GitHub Actions
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: blizz
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server called tony-de-rekenpony hosted by The Sysis team at KU Leuven"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - run: echo "The following commands are used to remove files inside container to ensure cleanup and avoid permission errors"
      - run: docker stop dymimg > /dev/null 2>&1 || true 
      - run: docker run --name dymimg --detach=true --rm -v /home/u0148284/actions-runner/_work/IDEAS/IDEAS:/home/developer/IDEAS -w /home/developer/IDEAS -it dymimg
      - run: docker exec -t dymimg /bin/bash -c "rm -rf IDEAS && exit"
      - run: docker stop dymimg > /dev/null 2>&1 || true
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          clean: true
      - name: Change permissions of repository folder
        run: chmod -R 777 /home/u0148284/actions-runner/_work
      - name: List of files in the repository
        run: | 
         ls ${{ github.workspace }}
  test:
    runs-on: blizz
    needs: build
    defaults:
      run:
        working-directory: IDEAS/Resources/Scripts/tests
    steps:
      - name: Test IDEAS.Airflow
        run: make test-dymola PACKAGE=\"IDEAS.Airflow\" INTERACTIVE=false
      - name: Test IDEAS.Buildings.Components
        run: make test-dymola PACKAGE=\"IDEAS.Buildings.Components\" INTERACTIVE=false
      - name: Test IDEAS.Buildings.Examples
        run: make test-dymola PACKAGE=\"IDEAS.Buildings.Examples\" INTERACTIVE=false
      - name: Test IDEAS.Buildings.Validation
        run: make test-dymola PACKAGE=\"IDEAS.Buildings.Validation\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Actuators
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Actuators\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.BaseClasses
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.BaseClasses\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Chillers
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Chillers\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Delays
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Delays\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Examples
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Examples\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.FixedResistances
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.FixedResistances\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Geothermal
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Geothermal\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.HeatExchangers
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.HeatExchangers\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.HeatPumps
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.HeatPumps\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Interfaces
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Interfaces\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.MassExchangers
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.MassExchangers\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.MixingVolumes
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.MixingVolumes\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Movers
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Movers\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Sensors
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Sensors\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Sources
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Sources\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Storage
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Storage\" INTERACTIVE=false
      - name: Test IDEAS.Fluid.Taps
        run: make test-dymola PACKAGE=\"IDEAS.Fluid.Taps\" INTERACTIVE=false
      - name: Test IDEAS.ThermalZones
        run: make test-dymola PACKAGE=\"IDEAS.ThermalZones\" INTERACTIVE=false
      - name: Test IDEAS.BoundaryConditions
        run: make test-dymola PACKAGE=\"IDEAS.BoundaryConditions\" INTERACTIVE=false
      - name: Test IDEAS.Controls
        run: make test-dymola PACKAGE=\"IDEAS.Controls\" INTERACTIVE=false
      - name: Test IDEAS.Media
        run: make test-dymola PACKAGE=\"IDEAS.Media\" INTERACTIVE=false
      - name: Test IDEAS.Utilities
        run: make test-dymola PACKAGE=\"IDEAS.Utilities\" INTERACTIVE=false
      - name: Test IDEAS.Templates
        run: make test-dymola PACKAGE=\"IDEAS.Templates\" INTERACTIVE=false
      - name: Test IDEAS.Examples.PPD12
        run: make test-dymola PACKAGE=\"IDEAS.Examples.PPD12\" INTERACTIVE=false
      - name: Test IDEAS.Examples.IBPSA
        run: make test-dymola PACKAGE=\"IDEAS.Examples.IBPSA\" INTERACTIVE=false
      - name: Test IDEAS.Examples.Tutorial
        run: make test-dymola PACKAGE=\"IDEAS.Examples.Tutorial\" INTERACTIVE=false
      - name: Test IDEAS.Examples.TwinHouses
        run: make test-dymola PACKAGE=\"IDEAS.Examples.TwinHouses\" INTERACTIVE=false
